name: 🪟 Windows Build

on:
  workflow_call:

jobs:
  windows-loader:
    name: "Build"
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download version.h artifact
      uses: actions/download-artifact@v4
      with:
        name: version-file
        path: src/loader/

    - name: Cache APT packages
      uses: actions/cache@v4
      with:
        path: /var/cache/apt/archives
        key: ${{ runner.os }}-apt-${{ hashFiles('**/install-packages.sh') }}
        restore-keys: |
          ${{ runner.os }}-apt-

    - name: Install Packages
      run: scripts/windows/install-packages.sh

    - name: Compile Build for Windows
      shell: bash
      run: scripts/windows/windows-build.sh

    - name: Upload linuxloader-win32.zip artifact
      uses: actions/upload-artifact@v4
      with:
        name: "windows-build" 
        path: "linuxloader-win32.zip"


